vanilla/porter

class.exportmodel.php, functions/filter-functions.php, functions/structure-functions.php, index.php, packages/vbulletin.php
* Use the correct charset in html_entity_decode
* Force the filter mapping to be used in vBulletin by preventing the `select as` alias from matching
=> Improve charset handling & fix vBulletin category name decoding

functions/filter-functions.php
MySQL character set names don't always match up with those recognized by html_entity_decode.  I added a small switch/case for translating the most common.
Supported charset names and aliases for html_entity_decode can be found here: http://php.net/html_entity_decode
=> HTML decode charset fix

class.exportcontroller.php, index.php
Adds error messages (and avoid fatals) for invalid package specification or when attempting to run in an environment without the MySQL extension installed or enabled
=> Updating error message reporting for package and MySQL; Fixes #53

class.exportcontroller.php, class.exportmodel.php, functions/commandline-functions.php, functions/render-functions.php, packages/phpbb3.php
Add the ability to export specific tables with the "tables" parameter.  If the parameter is passed/not empty, it should contain a comma-separated value of table names.  If ExportModel attempts to export a table that isn't specified in the list (all tables are included by default), the table is skipped.
Should be backwards-compatible with all existing packages.
ExportModel:: ShouldExport can be used in packages to determine if a table should be exported (useful for avoiding unnecessary temporary tables, etc).
Fixes #27
=> Adding ability to selective export tables

packages/ipb.php
Unless the prefix is 'ibf', the export will always fail without this fix.
=> IP Board: remove hard-coded table prefix which will halt export

packages/vbulletin.php
$this in anonymous function is not valid in 5.3.  It was introduced in 5.4.
=> vBulletin: Fixing anonymous function using $this

packages/phpbb3.php
topic_replies was dropped in phpBB 3.1.   This PR removes reliance on that database column.   The functionality is replaced by existing count operations following an import.
=> Dropping topic_replies from phpbb3 package

packages/vbulletin.php
Fix SQL error in 3.x import without 'filedata' table.
=> vb: Add  to other side of the union

packages/vbulletin5.php
vBulletin5 use BBCode and not Markdown
=> Change format from Markdown to BBCode in vBulletin5

class.exportcontroller.php, packages/bbpress.php, packages/simplepress.php
When using the porter via command line we absolutely need to specify a prefix for some packages even if we just want to use the default prefix.
With this PR, if we do not provide any prefix, it will use the default prefix defined in the $Support variable for that particular package!
=> Use default prefix when none is supplied

packages/advancedforum.php, packages/aspplayground.php, packages/bbpress.php, packages/drupal.php, packages/esotalk.php, packages/expressionengine.php, packages/ipb.php, packages/jforum.php, packages/kunena.php, packages/mbox.php, packages/mybb.php, packages/nodebb.php, packages/phpbb2.php, packages/phpbb3.php, packages/punbb.php, packages/simplepress.php, packages/smf.php, packages/smf2.php, packages/toast.php, packages/uservoice.php, packages/vanilla1.php, packages/vanilla2.php, packages/vbulletin.php, packages/vbulletin5.php, packages/webwiz.php, packages/xenforo.php, packages/yaf.php
Some packages used hardcoded prefixes on table instead of using ":_" which allows to use any prefixes.
This PR fixes that.
BONUS: Now all package do character set detection as suggested in tpl_package.txt
=> Fix prefixes and normalize character set determination.

packages/expressionengine.php, packages/ipb.php, packages/kunena.php, packages/phpbb3.php, packages/vanilla1.php, packages/vbulletin.php, packages/vbulletin5.php
There were references to an old method, StorageMethod, from the Media tables in multiple packages.
In some package it caused some fatal errors so I just removed references to it in all packages.
Also fixes #75
=> Remove references to column StorageMethod

packages/phpbb2.php
I fixed a broken query that requested an non-existing column on the user table.
Querying the user_group table should be enough.
=> Fix a broken query in the phpbb2 package

packages/bbpress2.php
Fix an exception to the coding standard... we need those closing php tags at the end of the packages!
When refactoring the code we should make it clear that they are mandatory.
See https://github.com/vanilla/porter/commit/144c5b6b9d3ab0fde76c77fc5840bec8f67ecc3d
=> Add missing php closing tag because make.php needs them.

functions/filter-functions.php, packages/expressionengine.php, packages/ipb.php, packages/kunena.php, packages/phpbb3.php, packages/punbb.php, packages/smf.php, packages/smf2.php, packages/vbulletin.php, packages/vbulletin5.php
Some packages do not fill ThumbPath and ThumbWith for images when exporting.
This PR is fixing that!
=> Fill ThumbPath and ThumbWidth columns in Media table.

class.exportcontroller.php
There was a problem with the old logic that put DEFAULT_PACKAGE as the prefix for a package with no prefix defined.
=> Fix code logic about default packages

packages/vbulletin5.php
There is a plugin for VB that allows comments on comments.
This feature is not supported in vanilla.
Exclude these comments from the exportation and add a warning about it.
=> Exclude inner comments from exportation + add a warning

packages/vbulletin.php
It is not fun when an index is missing...
It can be the difference between this:
and that:
The first run do 76910 X 2159741 comparisons. Takes hours ?!?
The second run do 76910 comparisons. Takes 6.44 seconds.
=> Fix index detection in vbulletin package.

packages/vbulletin.php
Remove discussions and comments DateUpdated field in  package vbulletin (3 & 4). Field was displaying the same information as DateInserted. Which makes the DateUpdated field obsolete.
=> Remove in package [vbulletin] discussions and comments DateUpdated field

packages/phpbb3.php
Include both 'stickied' and 'announced' discussion options as "Announce" in the export of the discussion table of the phpbb3 package.
Migrating topic_type 2 as a type 2 announcement in Vanilla to not over populate the recent discussions sections.
=> Include both 'stickied' and 'announced' discussion options 

functions/commandline-functions.php
Command line help was displaying "-s" instead of "-t" for selective table export
=> Command line help showed wrong shortcut for selective table export

packages/modxdiscuss.php, sample_package.php
The sample had shown `$Supported` as spelling for the `$supported` array.
=> Fix $supported array spelling in sample

packages/vbulletin.php
Some vBulletin discussions and/or comments include BBCode [ATTACH] tags.
For example:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
[ATTACH=CONFIG]71[/ATTACH]
```
Result is this after migration on Vanilla:
We are correctly migrating the attachment to the media table but displaying the [ATTACH] tag creates a "duplicate" of the same attachment as a link to the same file. More precisely:
```
<a …
```
=> Fix vbulletin package handling of BBcode ATTACH tag

functions/core-functions.php
When images are corrupted/too old GD crashes, which makes PHP crash.
Ignoring the first error and creating thumbnail from string when imagecreatefromjpeg doesn't work.
Closes https://github.com/vanilla/porter/issues/136
=> Fix imagecreatefromjpeg throwing fatal errors during blobs export

packages/drupal7.php
Only set DateUpdated when it's different from DateInserted (Comments and Discussions).
Change "RoldID" for "RoleID" in UserRole query.
Change "ForeinTable" for "ForeignTable" in Media query.
=> Drupal7: fix package

class.exportmodel.php, packages/class.hmdglobal.php
In some migrations, i.e. when temp tables are needed, it is useful to know if a table exists.
I added a generic function to query that information to the export model.
=> Add a table exists function to the export model

class.exportmodel.php
An undefined variable error will occur if the query result of the get function in the export model is empty.
```
Error in class.exportmodel.php line 541: (8) Undefined variable: result
```
This fix simply declares the $result variable and set it to an empty array by default.
=> Fix undefined variable in get function of export model

class.exportmodel.php, packages/mvc.php
* Added porter for MVC forums
* Comments
* Discussions
* Users
* Badge 
* Categories
* Roles
* Avatars
* Signatures
* Tags
* Attachments
* Extracted features are limited to the one mention in : [Ansys estimate](https://github.com/vanillaforums/estimates/blob/master/ansys/migration.estimate.md).
* Attachments have no size or type in the original db, will require an additional script to set properly. Said script can't be done as of this PR since the attachments files were not available. Writing this script is estimated at **one (1) hours**.
* The porter is slow when it come to features with a large number rows or multiple ID's like comments or discussions. This is due to the fact that all ID's have to be converted from GUID to integer using translation table to ensure the db integrity.
* …
=> Add MVC Porter package.

packages/vbulletin.php
Private messages from vBulletin were migrated even though the user deleted them. This is not GDPR compliant making it a pretty big deal. 
This issue is caused by the way vBulletin handles private messages deletion. Basically, private messages are only deleted when both parties delete the message. See: https://forum.vbulletin.com/forum/vbcloud/vbulletin-cloud-questions-problems-and-troubleshooting/4455093-deleted-%E2%80%98sent%E2%80%99-messages-still-visible?p=4455118#post4455118
Since there are no columns to indicate a message has been deleted or records in the log, the query to migrate the conversation was changed in such a way that only messages where both parties can still see the message will get migrated.
I also took the opportunity to consolidate and optimize the queries used to …
=> fix migrating deleted messages from vBulletin

packages/answerhub.php
* AnswerHub porter was not able to migrate attachments or discussion tags.
* Hardcoded table prefix was too restrictive.
* Attachments
* Tags
* Discussion Tags
* Removed unnecessary hardcoded prefix.
=> added attachments and tags to AnswerHub porter

functions/structure-functions.php
Add the following missing fields to the migration schema.
- GDN_Discussion.statusID
- GDN_UserCategory.Followed
- GDN_UserCategory.DateFollowed
- GDN_UserCategory.DateUnFollowed
=> add missing fields
