packages/yaf.php
=> fix yaf import

packages/vbulletin.php
Adding ThumbPath to imported image attachments in vBulletin package
=> vBulletin: Adding ThumbPath to imported image attachments

utilities/phpbb.extensions.php
phpbb.extensions.php has been updated to fix error-throwing procedural mysqli_* functions and incorrect file renaming.
=> Fixing miscellaneous errors in utility/phpbb.extensions.php

class.exportcontroller.php, class.exportmodel.php
I couldn't find any real use for UseStreaming.  It was primarily set to false, except for when it was attempting to be set by a POST variable that isn't used in the application.  Issue #38 proposed killing it, so I've killed it.
I've run test migrations from CLI and web.  Both seemed to turn out A-OK after removal of UseStreaming.
Fixes #38
=> Removing UseStreaming

packages/esotalk.php
- Fixes the problem I mentioned in #47 in regards to not getting replies to a thread
- Fixes some missing operands for prefix too.
=> Update esoTalk package

functions/core-functions.php
Pretty much what the title says.
=> Add file and line number to errors. Waaaaay easier to track them down!

packages/bbpress2.php
=> Add bbPress2 package! Hurray!

functions/commandline-functions.php
=> Fix destpath default parameter.

packages/drupal.php
=> Add export private messages functionality to Drupal6 package

packages/vbulletin.php
=> Fix discussion field "Type" for polls in the vbulletin package

packages/vbulletin.php
Shameful PR.
It is tested and its working now.
=> Define the Type column on the proper table

index.php
=> Update version to 2.3

packages/vbulletin.php
=> Update code formatting of vbulletin package.

class.exportcontroller.php, functions/core-functions.php
Especially when using the porter in CLI mode :D
=> Max execution time should be increased not set.

packages/fusetalk.php
=> Add Fusetalk package

packages/jforum.php
Rewrite queries (optimize)
+ detection of the post_text table.
=> Fix jForum package. Detect if post_text table exists or not.

class.exportmodel.php, packages/vbulletin.php
Update the vBulletin package to be 3.0.5 compatible.
Also add some optimizations.
=> Update the vBulletin package to be 3.0.5 compatible.

packages/vbulletin.php
showthread.php?p={ForeignID} will now work.
=> Add ForeignID to vBulletin discussions so that "posts" redirects work properly.

packages/vbulletin.php
Be sure to export the collected users' meta information.
=> Fix vBulletin user's meta export.

packages/fusetalk.php
There is an expiration date on the announcements...
=> Fix announcements expirations (Fusetalk)

packages/fusetalk.php
=> Add signatures and ban status

packages/esotalk.php
See https://github.com/vanilla/porter/pull/76#issuecomment-244340253
Thanks to @jamesn81
=> Fix Discussion query in esotalk package.

packages/fusetalk.php
The package was checking only for email banning.
=> Check for nickname banning in the FuseTalk package

functions/commandline-functions.php
Original: https://github.com/vanilla/porter/pull/140
=> Fix --help

packages/codoforum.php
A package to export data from CodoForum. Simple but effective. Tested with CodoForum 3.7.2, but should work with any version of CodoForum 3.
=> Support for CodoForum 3

packages/fluxbb.php
This is a follow up of this PR (https://github.com/vanilla/porter/pull/145)
=> Add fluxbb package to the porter

composer.json
Getting error emails from Packagist about this.
=> Correct composer.json license

class.exportcontroller.php, functions/render-functions.php, index.php
This fixes the XSS vulnerabilities listed in a hackerone ticket we received a while ago.
Original issue: https://github.com/vanilla/porter/issues/165
=> Fix XSS vunerabilities

index.php
Update porter version from 2.3 to 2.5.
=> Increment porter current version

packages/punbb.php
The punbb's signature migration is not complete for the signature plugin to work. Added not script to help migrate signature for punbb.
=> Fix signature query in PunBB package

packages/phpbb3.php
* Added more user discussions data.
=> added viewed post to GDN_UserDiscussion

packages/xenforo.php
Xenforo Media query was scaling very badly when xf_post and xf_thread were too large
Rewrote the query to be more efficient.
=> Rewrote Xenforo Media query due to performance issues

packages/vbulletin.php
Removed unnecessary die as pointed out here: https://github.com/vanilla/porter/pull/210
=> removed die

class.exportmodel.php, packages/vbulletin.php
* Replace curly brackets with square brackets.
=> fix deprecated synthax
